<center> <h2>Interactive Python - Week 7</h2> </center>
<center> <h3>---------------------------------------</h3> </center>

####*Video 7.1 - Acceleration and Friction*

**A. Notes**

- we will spend the last two weeks making Asteroids
- left key (rotate counterclockwise), right key (rotate clockwise)
    - speed is controlled by acceleration, not velocity
- adding friction:
    - ship generally slows if it isn't being accelerated
    
**B. Basic Physics**

- position update: ```position += velocity```
- velocity update: ```velocity += acceleration```
- variables for the ship class:
    - self.pos = ship's position (vector)
    - self.vel = ship's velocity (vector)
    - self.angle = ship's orientation (scalar)
    - self.thrust = is the ship accelerating? (boolean)
- velocity update - acceleration in direction of forward vector
    - forward = [math.cos(self.angle), math.sin(self.angle)]
    - if self.thrust:
    -   self.vel[0] += forward[0]
    -   self.vel[1] += forward[1]
- update position then velocity
- go back to this lecture to see more notes and sample code

####*Video 7.2 - Spaceship Class*

**A. Notes**

```{r eval=FALSE}
# Partial example code for Spaceship

import simplegui


class ImageInfo:
    def __init__(self, center, size, radius = 0, lifespan = None, animated = False):
        self.center = center
        self.size = size
        self.radius = radius
        if lifespan:
            self.lifespan = lifespan
        else:
            self.lifespan = float('inf')
        self.animated = animated

    def get_center(self):
        return self.center

    def get_size(self):
        return self.size

    def get_radius(self):
        return self.radius

    def get_lifespan(self):
        return self.lifespan

    def get_animated(self):
        return self.animated

    
# art assets created by Kim Lathrop, may be freely re-used in non-commercial projects, please credit Kim
    
# ship image
ship_info = ImageInfo([45, 45], [90, 90], 35)
ship_image = simplegui.load_image("http://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/double_ship.png")

# sound assets purchased from sounddogs.com, please do not redistribute
ship_thrust_sound = simplegui.load_sound("http://commondatastorage.googleapis.com/codeskulptor-assets/sounddogs/thrust.mp3")


# Ship class
class Ship:
    def __init__(self, pos, vel, angle, image, info):
        self.pos = [pos[0],pos[1]]
        self.vel = [vel[0],vel[1]]
        self.thrust = False
        self.angle = angle
        self.angle_vel = 0
        self.image = image
        self.image_center = info.get_center()
        self.image_size = info.get_size()
        self.radius = info.get_radius()
        
    def draw(self,canvas):
        canvas.draw_circle(self.pos, self.radius, 1, "White", "White")

    def update(self):
        pass
```

- two images: with or without thrustster
    - you will also need to rotate based on velocity lecture

####*Video 7.3 - Sounds*

**A. Playing Sounds is Straightforward**

- the hardest part can be just finding your own sounds
- sounds are associated with codeskultptor, not the frame (so you need to reset!)
- implement in Chrome! (firefox sucks with sounds)
- 